version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - mvn package -DskipTests
      - mv target/twitter-0.0.1-SNAPSHOT.jar twitter.jar

artifacts:
  files:
    - twitter.jar
    - Procfile
    - .platform/**/*
